version: '3'

services:
  tax-id-validator:
    entrypoint: /bin/sh './entrypoint-prod.sh'
    container_name: tax-id-validator
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app/
